# Generated by Django 4.2.4 on 2023-08-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default='null', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
    ]
