# Generated by Django 4.2.4 on 2023-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_curriculum_alter_course_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='heading',
            field=models.TextField(default='hey'),
            preserve_default=False,
        ),
    ]
