# Generated by Django 4.2.4 on 2023-08-31 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('link', 'link')], default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='youtubeLink',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default='r', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, upload_to='resources/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
