# Generated by Django 4.2.4 on 2023-08-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_resource_file_type_resource_youtubelink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pastquestion',
            name='description',
        ),
    ]
