# Generated by Django 4.2.4 on 2023-08-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_learningstyle_user_class_type_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_level',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='math_grade',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='math_strength',
            field=models.CharField(default='A', max_length=30),
            preserve_default=False,
        ),
    ]
