# Generated by Django 4.2.4 on 2023-08-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_class_level_user_math_grade_user_math_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='class_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='math_grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='math_strength',
            field=models.CharField(max_length=10),
        ),
    ]
