# Generated by Django 4.2.4 on 2023-08-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_class_type_alter_user_class_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_learning_style',
        ),
        migrations.RemoveField(
            model_name='user',
            name='learning_style',
        ),
        migrations.AddField(
            model_name='user',
            name='auditory_learner',
            field=models.BooleanField(default=False, verbose_name='Auditory Learner'),
        ),
        migrations.AddField(
            model_name='user',
            name='kinesthetic_learner',
            field=models.BooleanField(default=False, verbose_name='Kinesthetic Learner'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_write_learner',
            field=models.BooleanField(default=False, verbose_name='Read/Write Learner'),
        ),
        migrations.AddField(
            model_name='user',
            name='visual_learner',
            field=models.BooleanField(default=False, verbose_name='Visual Learner'),
        ),
        migrations.DeleteModel(
            name='LearningStyle',
        ),
    ]
