# Generated by Django 4.2.4 on 2023-08-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_is_learning_style_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auditory_learner',
            new_name='is_auditory_learner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='kinesthetic_learner',
            new_name='is_kinesthetic_learner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='read_write_learner',
            new_name='is_read_write_learner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='visual_learner',
            new_name='is_visual_learner',
        ),
    ]
